name: CI

on:
    push:
    workflow_dispatch:

jobs:
    build-executable:
        runs-on: ubuntu-latest
        steps:
            -   name: Check out the repo
                uses: actions/checkout@v3

            -   name: Set up Node v18
                uses: actions/setup-node@v3
                with:
                   node-version: 18
                   cache: 'yarn'

            -   name: Install dependencies
                run: yarn install

            -   name: Build, compile and package the app
                run: yarn export

            -   name: Upload executable
                uses: actions/upload-artifact@v3
                with:
                    name: sudoku
                    path: dist/sudoku.exe
